import sys

Import('env')

ori_env = env.Clone()

src = [
    "cmd_addkey.cc",
    "cmd_branch.cc",
    "cmd_branches.cc",
    "cmd_checkout.cc",
    "cmd_commit.cc",
    "cmd_diff.cc",
    "cmd_filelog.cc",
    "cmd_findheads.cc",
    "cmd_gc.cc",
    "cmd_graft.cc",
    "cmd_init.cc",
    "cmd_list.cc",
    "cmd_listkeys.cc",
    "cmd_log.cc",
    "cmd_merge.cc",
    "cmd_newfs.cc",
    "cmd_pull.cc",
    "cmd_purgesnapshot.cc",
    "cmd_remote.cc",
    "cmd_removefs.cc",
    "cmd_removekey.cc",
    "cmd_replicate.cc",
    "cmd_setkey.cc",
    "cmd_show.cc",
    "cmd_snapshot.cc",
    "cmd_snapshots.cc",
    "cmd_status.cc",
    "cmd_tip.cc",
    "cmd_treediff.cc",
    "main.cc",
    "server.cc",
]

libs = [
	"crypto",
	"stdc++",
	"event_core",
	"event_extra",
]

if sys.platform != "darwin":
    libs += ['rt']
    if env["WITH_MDNS"]:
        libs += ['dns_sd']

if sys.platform == "linux2":
    libs += ['uuid', 'resolv']

ori_env.Append(LIBS = libs)

ori_env.Program("orilocal", src)

