import sys

Import('env')

orisync_env = env.Clone()

src = [
    "orisyncconf.cc",
    "cmd_init.cc",
    "cmd_add.cc",
    "cmd_remove.cc",
    "cmd_list.cc",
    "cmd_hostadd.cc",
    "cmd_hostremove.cc",
    "cmd_hosts.cc",
    "main.cc",
    "repocontrol.cc",
    "server.cc",
]

libs = [
    "oriutil",
    "ori",
    "fastlz",
    "crypto",
    "stdc++",
    "event_core",
    "event_extra",
]

if sys.platform != "darwin":
    libs += ['rt', 'pthread']
    if env["WITH_MDNS"]:
        libs += ['dns_sd']

if sys.platform == "linux2":
    libs += ['uuid', 'resolv']

orisync_env.Append(LIBS = libs)

orisync_env.Program("orisync", src)

