import sys

Import('env')

src = [
    "chunker.cc",
    "commit.cc",
    "largeblob.cc",
    "main.cc",
    "debug.cc",
    "object.cc",
    "repo.cc",
    "repo_cmd.cc",
    "scan.cc",
    "tree.cc",
    "util.cc",
    "stream.cc",
    "server.cc",
    "sshclient.cc",
]

libs = [
        "crypto",
        "stdc++",
        "lzma",
        "microhttpd",
       ]
if sys.platform == "darwin":
    # TODO
    libs += []
else:
    libs += ['rt']

env.Program("ori", src,
            LIBPATH = [ "$LIBPATH" ],
	    LIBS = libs,
            CPPPATH = [ "$CPPPATH", "#include", "#" ])

