Import('env')

src = [
    "commit.cc",
    "largeblob.cc",
    "main.cc",
    "object.cc",
    "rabinkarp.cc",
    "repo.cc",
    "repo_cmd.cc",
    "scan.cc",
    "tree.cc",
    "util.cc",
]

env.Program("ori", src,
            LIBPATH = [ "$LIBPATH" ],
	    LIBS = [ "crypto", "stdc++", "rt" ],
            CPPPATH = [ "$CPPPATH", "#include", "#" ])

