/*
 * Copyright (c) 2012 Stanford University
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR(S) DISCLAIM ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL AUTHORS BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef __FUSE_TUNEABLES_H__
#define __FUSE_TUNEABLES_H__

// FUSE tuneables
#ifdef DEBUG
#define FUSE_TREE_CACHE_SIZE		128
#define FUSE_LARGEBLOB_CACHE_SIZE	64
#define FUSE_OBJINFO_CACHE_SIZE		128
#define FUSE_NLINK_CACHE_SIZE		128
#define FUSE_ENTRY_CACHE_SIZE		512
#else /* Performance or Relase Build */
#define FUSE_TREE_CACHE_SIZE		1024
#define FUSE_LARGEBLOB_CACHE_SIZE	64
#define FUSE_OBJINFO_CACHE_SIZE		(4 * 1024)
#define FUSE_NLINK_CACHE_SIZE		1024
#define FUSE_ENTRY_CACHE_SIZE		(4 * 1024)
#endif
#define FUSE_SINGLE_THREADED 0

#endif /* __FUSE_TUNEABLES_H__ */

