import sys

Import('env')

src = [
    "ori_fuse.cc",
    "parse_opt.cc",
]

libs = [
        "crypto",
        "fuse",
        "lzma",
        "ori",
        ]

if sys.platform == "darwin":
    libs += []
else:
    libs += ['rt']

env.Program("mount_ori", src,
            LIBPATH = [ "#build/libori", "$LIBPATH" ],
            LIBS = libs,
            CPPPATH = [ "#libori", "$CPPPATH", "#include", "#" ])

