import sys

Import('env')

src = [
    "ori_fuse.cc",
    "parse_opt.cc",
    "ori_priv.cc",
    "logging.cc",
]

libs = [
        "crypto",
        "lzma",
        "ori",
        ]

if sys.platform == "darwin":
    env.ParseConfig('pkg-config --libs --cflags fuse')
else:
    libs += ['fuse', 'rt']
    
env.Append(
        LIBS = libs,
        LIBPATH = [ "#build/libori", "$LIBPATH" ],
        CPPPATH = [ "#libori", "$CPPPATH", "#include", "#" ]
        )

env.Program("mount_ori", src)
