import os
import sys

Import('env')

src = [
    "dag.cc",
    "debug.cc",
    "key.cc",
    "kvserializer.cc",
    "lrucache.cc",
    "monitor.cc",
    "objecthash.cc",
    "objectinfo.cc",
    "oricrypt.cc",
    "orifile.cc",
    "orinet.cc",
    "oristr.cc",
    "oriutil.cc",
    "rwlock.cc",
    "stopwatch.cc",
    "stream.cc",
]

if os.name == 'posix':
    src += ['mutex_posix.cc', 'rwlock_posix.cc', 'thread_posix.cc']
else:
    print "Error unsupported operating system!"

if env["WITH_MDNS"]:
    src.append("zeroconf.cc")

env.StaticLibrary("oriutil", src)

# Test Binaries
if env["BUILD_BINARIES"]:
    env_testori = env.Clone()
    libs = ["crypto", "stdc++"]
    if sys.platform != "darwin":
        libs += ['rt']
    if sys.platform == "linux2":
        libs += ['uuid', 'resolv']
    env_testori.Append(LIBS = libs)
    env_testori.Program("test_oriutil", "test_oriutil.cc")

