import sys

Import('env')

src = [
    "s3backup.cc",
    "oris3.cc",
]

libs = [
	"crypto",
	"stdc++",
	"event_core",
	"event_extra",
	"libs3",
	"libxml2",
	"curl",
       ]

if sys.platform != "darwin":
    libs += ['rt']
    if env["WITH_MDNS"] == "1":
        libs += ['dns_sd']

if sys.platform == "linux2":
    libs += ['uuid', 'resolv']

env.Append(LIBPATH = ["#build/libs3-2.0"],
	   CPPPATH = ["#libs3-2.0"],
	   LIBS = libs)

env.Program("oris3", src)

