import os

Import('env')

src = [
    "commit.cc",
    "dag.cc",
    "debug.cc",
    "httpclient.cc",
    "httprepo.cc",
    "index.cc",
    "key.cc",
    "largeblob.cc",
    "localobject.cc",
    "localrepo.cc",
    "lrucache.cc",
    "mergestate.cc",
    "monitor.cc",
    "object.cc",
    "peer.cc",
    "repo.cc",
    "remoterepo.cc",
    "snapshotindex.cc",
    "sshclient.cc",
    "sshrepo.cc",
    "stream.cc",
    "tempdir.cc",
    "tree.cc",
    "treediff.cc",
    "oriutil.cc",
    "metadatalog.cc",
    "objecthash.cc",
    "packfile.cc",
    "rwlock.cc",
]

if os.name == 'posix':
    src += ['mutex_posix.cc', 'rwlock_posix.cc', 'thread_posix.cc']
else:
    print "Error unsupported operating system!"

if env["WITH_MDNS"] == "1":
    src.append("zeroconf.cc")

if env["WITH_LIBS3"] == "1":
    src.append("backup_s3.cc")

env.StaticLibrary("ori", src)

# Test Binaries
env.Program("rkchunker", "rkchunker.cc")
env.Program("fchunker", "fchunker.cc")

