import os

Import('env')

src = [
    "commit.cc",
    "evbufstream.cc",
    "httpclient.cc",
    "httprepo.cc",
    "httpserver.cc",
    "index.cc",
    "largeblob.cc",
    "localobject.cc",
    "localrepo.cc",
    "mergestate.cc",
    "metadatalog.cc",
    "object.cc",
    "packfile.cc",
    "peer.cc",
    "repo.cc",
    "repostore.cc",
    "remoterepo.cc",
    "snapshotindex.cc",
    "sshclient.cc",
    "sshrepo.cc",
    "tempdir.cc",
    "tree.cc",
    "treediff.cc",
    "udsclient.cc",
    "udsrepo.cc",
    "udsserver.cc",
    "varlink.cc",
]

env.StaticLibrary("ori", src)

# Test Binaries
if env["BUILD_BINARIES"]:
    env.Program("rkchunker", "rkchunker.cc")
    env.Program("fchunker", "fchunker.cc")

