import sys

Import('env')

src = [
    "httpd.cc",
    "evbufstream.cc",
]

libs = [
        "crypto",
        "stdc++",
        "lzma",
        "ori",
       ]

if sys.platform == "darwin":
    libs += ['resolv']
else:
    libs += ['rt']
    if env["WITH_MDNS"] == "1":
        libs += ['dns_sd']

if sys.platform == "linux2":
    libs += ['uuid', 'resolv']

env.Append(LIBPATH = [ "#build/libori", "$LIBPATH" ],
            LIBS = libs,
            CPPPATH = [ "#libori", "$CPPPATH", "#include", "#" ])

env.Program("ori_httpd", src)

