import sys

Import('env')

src = [
    "logging.cc",
    "oricmd.cc",
    "orifuse.cc",
    "oripriv.cc",
    "oriopt.cc",
]

libs = [
        "ori",
        "oriutil",
        "fastlz",
        "crypto",
        ]

env.ParseConfig('pkg-config --libs --cflags fuse')
if sys.platform != "darwin":
    libs += ['rt', 'pthread']

env.Append(LIBS = libs, CPPPATH = [ "$CPPPATH", "#include", "#" ])

env.Program("orifs", src)
