import sys

Import('env')

orifs_env = env.Clone()

src = [
    "logging.cc",
    "oricmd.cc",
    "orifuse.cc",
    "oripriv.cc",
    "oriopt.cc",
]

libs = [
    "ori",
    "oriutil",
    "fastlz",
    "crypto",
]

orifs_env.ParseConfig('pkg-config --libs --cflags libevent')
orifs_env.ParseConfig('pkg-config --libs --cflags fuse')
if sys.platform != "darwin":
    libs += ['rt']
if sys.platform == "linux2":
    libs += ['uuid']

orifs_env.Append(LIBS = libs, CPPPATH = [ "$CPPPATH", "#include", "#" ])

orifs_env.Program("orifs", src)
